name: Demo puppeteer script

on:
  workflow_dispatch:

jobs:

  demo:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@master


    - name: Install
      uses: IORoot/action__puppeteer--media@master
      with:
        args: npm install


    - name: Test Code
      uses: IORoot/action__puppeteer--media@master
      with:
        args: node puppeteer.js
