name: (RUN) Instagram Scheduler

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: londonparkour/igs:latest
      credentials:
        username: londonparkour
        password: ${{ secrets.docker_hub_password}}

    steps:

    - run: |
      echo This job does specify a container.
      echo $HOME
