name: (RUN) Instagram Scheduler

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    services:
      myservice1:
        image: londonparkour/igs:latest
        credentials:
          username: londonparkour
          password: ${{ secrets.docker_hub_password}}
        ports:
          - 8080:8080

    steps:
      - uses: actions/checkout@v1

      # Open Ports
      - name: IPTables all ports open
        run: |
          sudo iptables -I INPUT -j ACCEPT

      # Install Stuff
      - name: Install Software
        run: |
          sudo apt update -y
          sudo apt install -y procps
          alias ll="ls -la"

      # Ports 22 (ssh) & 80 (http)
      - name: Custom NGROK SSH Action
        uses: ./.github/actions/ngrok
        with:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
          SSH_PASS: ${{ secrets.NGROK_SSH_PASS }}
          NGROK_REGION: eu
          NGROK_REGION_ALT: us
          NGROK_PORT: 80
          NGROK_PROTO: 'http'
