name: (RUN) Instagram Scheduler

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    container:
      image: londonparkour/igs:latest
      credentials:
        username: londonparkour
        password: ${{ secrets.docker_hub_password}}

    steps:

      - name: echo something
        run: |
          echo $HOME

      # DEBUG with NGROK.
      # - name: Start SSH session
      #   uses: luchihoratiu/debug-via-ssh@main
      #   with:
      #     NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
      #     SSH_PASS: ${{ secrets.NGROK_SSH_PASS }}
      #     NGROK_REGION: eu

      - name: Start SSH via Ngrok
        run: wget -O- https://gist.githubusercontent.com/retyui/7115bb6acf151351a143ec8f96a7c561/raw/7099b9db76729dc5761da72aa8525f632d8875c9/debug-github-actions.sh | bash
        env:
          NGROK_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
          USER_PASS: ${{ secrets.USER_PASS }}
