name: (RUN) Instagram Scheduler

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    container:
      image: londonparkour/igs:latest
      credentials:
        username: londonparkour
        password: ${{ secrets.docker_hub_password}}